/* Style */
/*String style =
  "<style>#file-input,input{width:100%;height:44px;border-radius:4px;margin:10px auto;font-size:15px}"
  "input{background:#f1f1f1;border:0;padding:0 15px}body{background:#3498db;font-family:sans-serif;font-size:14px;color:#777}"
  "#file-input{padding:0;border:1px solid #ddd;line-height:44px;text-align:left;display:block;cursor:pointer}"
  "#bar,#prgbar{background-color:#f1f1f1;border-radius:10px}#bar{background-color:#3498db;width:0%;height:10px}"
  "form{background:#fff;max-width:258px;margin:75px auto;padding:30px;border-radius:5px;text-align:center}"
  ".btn{background:#3498db;color:#fff;cursor:pointer}</style>";
  */
String style = "";

/* update Index Page */
String updateIndex = "<!DOCTYPE HTML><html>\n"
                     "<head>\n"
                     "  <title>OBS Control</title>\n"
                     "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                     + style +
                     "</head>\n"
                     "<body>\n"
                     "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
                     "<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
                     "  <input type='file' name='update' id='file' onchange='sub(this)' style=display:none>"
                     "  <label id='file-input' for='file'>   Choose file...</label>"
                     "  <input type='submit' class=btn value='Update'>"
                     "  <br><br>"
                     "  <div id='prg'></div>"
                     "  <br><div id='prgbar'><div id='bar'></div></div><br>"
                     "</form>"
                     "<script>"
                     "  function sub(obj){"
                     "    var fileName = obj.value.split('\\\\');"
                     "    document.getElementById('file-input').innerHTML = '   '+ fileName[fileName.length-1];"
                     "  };"
                     "  $('form').submit(function(e){"
                     "    e.preventDefault();"
                     "  var form = $('#upload_form')[0];"
                     "  var data = new FormData(form);"
                     "  $.ajax({"
                     "    url: '/upload',"
                     "    type: 'POST',"
                     "    data: data,"
                     "    contentType: false,"
                     "    processData:false,"
                     "    xhr: function() {"
                     "  var xhr = new window.XMLHttpRequest();"
                     "  xhr.upload.addEventListener('progress', function(evt) {"
                     "    if (evt.lengthComputable) {"
                     "      var per = evt.loaded / evt.total;"
                     "      $('#prg').html('progress: ' + Math.round(per*100) + '%');"
                     "      $('#bar').css('width',Math.round(per*100) + '%');"
                     "    }"
                     "  }, false);"
                     "  return xhr;"
                     "  },"
                     "  success:function(d, s) {"
                     "  console.log('success!') "
                     "  },"
                     "  error: function (a, b, c) {"
                     "  }"
                     "  });"
                     "  });"
                     "</script>"
                     "</body>\n"
                     "</html>\n";

String index_html_head = "<!DOCTYPE HTML><html>\n"
                         "<head>\n"
                         "  <title>OBS Control</title>\n"
                         "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                         + style +
                         "</head>\n"
                         "<body>\n"
                         "  <h2>Scenes</h2>\n"
                         "    <label class=\"switch\">\n";

String index_html_tail = "    </label>\n"
                         "    To change OBS connection go to /set/host:port<br>\n"
                         "    To reset go to /reset<br>\n"
                         "    To upload new firmware go to /update<br>\n"
                         "    \n"
                         "<script>function toggleCheckbox(element) {\n"
                         "  var xhr = new XMLHttpRequest();\n"
                         "  if(element.checked){ xhr.open(\"GET\", \"/update?state=1\", true); }\n"
                         "  else { xhr.open(\"GET\", \"/update?state=0\", true); }\n"
                         "  xhr.send();\n"
                         "}\n"
                         "\n"
                         "setInterval(function ( ) {\n"
                         "  var xhttp = new XMLHttpRequest();\n"
                         "  xhttp.onreadystatechange = function() {\n"
                         "    if (this.readyState == 4 && this.status == 200) {\n"
                         "      var inputChecked;\n"
                         "      var outputStateM;\n"
                         "      if( this.responseText  == 1){ \n"
                         "        document.getElementById(\"output1\").checked = true;\n"
                         "        outputStateM = \"1\";\n"
                         "      } else if( this.responseText == 2){ \n"
                         "        document.getElementById(\"output2\").checked = true;\n"
                         "        outputStateM = \"2\";\n"
                         "      } else if( this.responseText == 3){ \n"
                         "        document.getElementById(\"output3\").checked = true;\n"
                         "        outputStateM = \"3\";\n"
                         "      } else if( this.responseText == 4){ \n"
                         "        document.getElementById(\"output4\").checked = true;\n"
                         "        outputStateM = \"4\";\n"
                         "      } else if( this.responseText == 5){ \n"
                         "        document.getElementById(\"output5\").checked = true;\n"
                         "        outputStateM = \"5\";\n"
                         "      } else if( this.responseText == 6){ \n"
                         "        document.getElementById(\"output6\").checked = true;\n"
                         "        outputStateM = \"6\";\n"
                         "      } else if( this.responseText == 7){ \n"
                         "        document.getElementById(\"output7\").checked = true;\n"
                         "        outputStateM = \"7\";\n"
                         "      } else if( this.responseText == 8){ \n"
                         "        document.getElementById(\"output8\").checked = true;\n"
                         "        outputStateM = \"8\";\n"
                         "      } else if( this.responseText == 9){ \n"
                         "        document.getElementById(\"output9\").checked = true;\n"
                         "        outputStateM = \"9\";\n"
                         "      } else if( this.responseText == 10){ \n"
                         "        document.getElementById(\"output10\").checked = true;\n"
                         "        outputStateM = \"10\";\n"
                         "      } else {\n"
                         "        inputChecked = false;\n"
                         "        outputStateM = \"Off\";\n"
                         "      }\n"
                         "      document.getElementById(\"outputState\").innerHTML = outputStateM;\n"
                         "    }\n"
                         "  };\n"
                         "  xhttp.open(\"GET\", \"/state\", true);\n"
                         "  xhttp.send();\n"
                         "}, 1000 ) ;\n"
                         "</script>\n"
                         "</body>\n"
                         "</html>\n";
